; PlatformIO Project Configuration File
; Smart Blind Assistant - ESP32-C3 BLE Firmware
;
; Komunikasi via BLE (bukan WiFi) ke app Flutter

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp> -<test_button.cpp>

lib_deps =
    h2zero/NimBLE-Arduino@1.4.3
